emails:
  0987654321qA: s@c.com
  12345678P: m@n.com
  Dfg1234567: Dfg@gmail.com
  Edcrfv123: w@gmail.com
  Edcrfv1234: w@gmail.com
  Edcrfv12346789: w@gmail.com
  Hello1234: hello@gmail.com
  Hellos1234: Hellos1234@gmail.com
  Hi12345678: hi@gmail.com
  Poqr1234: poqr@gmail.com
  Qazxs123: Qazxs@gmail.com
  Qscvf123: fere@f.com
  Qwert6789: wee@f.com
  Qwerty123456: r@gmail.com
  Ranjan123456: ranjan@g.com
  Werty4455: w@gmail.com
  Xyz1234: sd@m.com
  abc12345678: abc@s.com
  abc1234567809: abc@s.com
  agent1234: ag@d.com
  agent12345: ag@d.com
  errr: w@gmail.com
  g: g
  h: h
  hi1234: hi@gmail.com
  q: q
  qwert1234: cde@f.com
  raj12: raj@gmail.com
  raj12345678: Toraj12@abv.com
  rajesh: rajesh@gmail.com
  rishika: rishika@gmail.com
  s: s
  stockuser: stockuser@test.com
  swewerrrtQ1223: s@f.com
  system123: system@gmail.com
  w: w
  x: x
names:
  0987654321qA: zxc
  12345678P: m
  Dfg1234567: Dfg
  Edcrfv123: ertyy
  Edcrfv1234: ertyy
  Edcrfv12346789: ertyy
  Hello1234: hello
  Hellos1234: Hellos
  Hi12345678: hi
  Poqr1234: poqr
  Qazxs123: Qazxs
  Qscvf123: errr
  Qwert6789: tyui
  Qwerty123456: Ranjan
  Ranjan123456: Ranjan
  Werty4455: ertyy
  Xyz1234: xyz
  abc12345678: abc
  abc1234567809: abc
  agent1234: agent
  agent12345: agent
  errr: ertyy
  g: g
  h: h
  hi1234: hi
  q: q
  qwert1234: cde
  raj12: rajesh
  raj12345678: Rajesh
  rajesh: rajesh
  rishika: Rishika
  s: s
  stockuser: stockuser
  swewerrrtQ1223: erttt
  system123: system
  w: w
  x: x
passwords:
  0987654321qA: $2b$12$bZ6.aFwnBhz.A13KtzrC2OSc7LVMh2BFJ99OnotD3dwUXeQDTR9.i
  12345678P: $2b$12$YD58LYoCRn1C6MOpItnYmOso/5pAlZxxtTZTe.OqM2gIJeWq8MRRW
  Dfg1234567: $2b$12$sVwy3fnqLNAddVI3SFytKO6h3iqWQOFlFML8/yBR1u5onJsc2Lb0G
  Edcrfv123: $2b$12$139L8vlKUbszVatnTUARyOUCYoE3JrTq3Pk3vTKjJBrSXWnLV2vLS
  Edcrfv1234: $2b$12$CEgwT7Sp7kzAgV9JQ01YNucznxE6s/NlL2Tp8Amzg8Jhw1UGIEVFS
  Edcrfv12346789: $2b$12$jEyxKyZDA5LAVVElf2M1RuxTohl07VKig3g3ECNsMNW0tam1Fdh6W
  Hello1234: $2b$12$5WQ4fLHtxEWmfso4hvUlXuD89q3PPFLtZzKWb3hhWM7vQ2FmH/ZrK
  Hellos1234: $2b$12$9JdabwWsVJgllmKE6P58luqQS1pHs7J6AVzwIE9Bp/OFHZFo7tl6O
  Hi12345678: $2b$12$B7FntSzGVgATL1iHaFIoOuyOrZiFiTcEpbxg1QT8URJInxKhs/n82
  Poqr1234: $2b$12$sHmcBq9dj9NXHqiJWmOg3eJnEvZzqPMiLVfMTPV2.y9mGolINlA2u
  Qazxs123: $2b$12$8pLFdNR5gLukCCyN8aluw.y8Kqmea2/WaDDqW.IMvG0O40k.DTo2i
  Qscvf123: $2b$12$mWGmUKKcPf/qZAlEO7fdj.JhcN4goP7BEd5eH5ajbmo.A2j3hmLxG
  Qwert6789: $2b$12$XWWm231ZhzCORdJMr2QTMO1x/RNOym.wkztZO2WJ2r17lAxXy1d.a
  Qwerty123456: $2b$12$92H/DYG77dVcP9bTvOzlzuF/IKvXl0pUydmqamwz6UoaUsT./ynWm
  Ranjan123456: $2b$12$Rc6qAE6/ZqyaBHKUACGCKOk1yTtCx.qXw.4EhvuKLZP4BMnFQuC1.
  Werty4455: $2b$12$Ssg8QTL3x4AOUoR/8SfLtuPT6BFGVYQDe0U/Y087gFcnWyDZuo88u
  Xyz1234: $2b$12$OL5BN7JVYBb4Tf7xBIgS5uilLAKIbLynM75l5Y6.KTniRHYIYsHIO
  abc12345678: $2b$12$paFQYrXFnJ22m4lbsftTaOky5sh3HzaVRvqvxs5jOGl0ICahp3zcW
  abc1234567809: $2b$12$/BR7u6h6cI.U8l8VZqophemboVhPhpCXlG1lIY/iJsxEx5ifb34AK
  agent1234: $2b$12$Yvp/Vmtf1VlF1u/oUrsLZuNs1jt9IHkfksNV0BO0DSpdkefKq4oBG
  agent12345: $2b$12$6L8Ygy5kMwEj3z7nPU9hcestedcwR9s93z/7iQaOPM6Vhn4oiSUkW
  errr: $2b$12$fJ.hLdnBoGiqQLJPxvv7COGo2Sxf/la2L2G.2YOqOE1jkT3Jvw3/u
  g: $2b$12$S1c7tJXdJKhMnmK5clUrBO6VzY0UqEYa9Bkn/GenpQoVkZ8XXF8yu
  h: $2b$12$/BIRZ4gNCqqxhuhBZOez1.19ViLiUPR4FM1qpTlijbHQaI4JG/SQy
  hi1234: $2b$12$2rODAkmRxVEGfn7K7YVOW.xTK3lzLUwSgep1EHKTS7W6AWgn316lW
  q: $2b$12$ovVRHNrzfI06rPydzS3t0.B3lssp5GU/YjFNyLL./8wYSTnhwZ00G
  qwert1234: $2b$12$3eZRFa5IP/uIyEoAK/fpfOGBYipvRics7B0.BaDDwYn84jrV2ay3u
  raj12: $2b$12$zBdAwKHwr2IYAL/kmK3f2.j85.yLURMV6S41CumXjIogwsvZCVq3O
  raj12345678: $2b$12$RIli1yV4BZUPiAYFZSXSRe84RnWaYUk1RdQFxMrU4qFVJ5q3Zfrw6
  rajesh: $2b$12$9mxky5JrYP6cc8qaRNySruqZkd3XLOSzIoV3VOqSMaYj4aQ3aER/O
  rishika: $2b$12$10IubmzZapz9oEIDy7KzZeCIYqex0PCIn1Y2yAhUjsPHkLlMFCcFq
  s: $2b$12$f0XRwB747t5p/OY3pPhcz.Bb3gMf2PVa0sW5XwT4O4JXqmM92KbM6
  stockuser: $2b$12$7BPi1uIj/AWE1i8mLNfiq.FUfLcVjxJ9IULAy9.Z4i0sb8tNZ3MVW
  swewerrrtQ1223: $2b$12$/7cxx4h4g2TOseli6OKCT.X.LBPNuDbd0fBHXrbZ2T18QpB0HspHq
  system123: $2b$12$fZ9bJE5eLjA5W4dhDe0H.uXkrZK1Xs0esz.yMaT5r7R5uavbfZL7m
  w: $2b$12$yqvvlRN73X1lq7LgzX7HpeMQRsfuDTR0tPaxWxrnjzRv5ayhR5vWS
  x: $2b$12$kcL8jrxG/mOD/00RAPNzLu6dAqarpaf4rM94UcQ4ozNjd8CDbH.yW
usernames:
  0987654321qA: 0987654321qA
  12345678P: 12345678P
  Dfg1234567: Dfg1234567
  Edcrfv123: Edcrfv123
  Edcrfv1234: Edcrfv1234
  Edcrfv12346789: Edcrfv12346789
  Hello1234: Hello1234
  Hellos1234: Hellos1234
  Hi12345678: Hi12345678
  Poqr1234: Poqr1234
  Qazxs123: Qazxs123
  Qscvf123: Qscvf123
  Qwert6789: Qwert6789
  Qwerty123456: Qwerty123456
  Ranjan123456: Ranjan123456
  Werty4455: Werty4455
  Xyz1234: Xyz1234
  abc12345678: abc12345678
  abc1234567809: abc1234567809
  agent1234: agent1234
  agent12345: agent12345
  errr: errr
  g: g
  h: h
  hi1234: hi1234
  q: q
  qwert1234: qwert1234
  raj12: raj12
  raj12345678: raj12345678
  rajesh: rajesh
  rishika: rishika
  s: s
  stockuser: stockuser
  swewerrrtQ1223: swewerrrtQ1223
  system123: system123
  w: w
  x: x
